### ISSUE TITLE
[0.0.3] Sig. fault when exiting

### ISSUE THREAD

**Issue by ArtemPopof** [abbysoft-team/Soompler#39]

**Comment by ArtemPopof** [comment]
I cannot find a problem with plugin code. Seems like problem in JUCE framework. For some reason window field of AudioThumbnail class is deleted before it used in AudioThumbnail destructor.

**Comment by ArtemPopof** [comment]
Wrote about this issue at JUCE forum, maybe someone can point where this issue origin is.

**Comment by ArtemPopof** [comment]
Regression is spotted in 0.0.4 development branch

**Comment by JorgenPo** [comment]
Is it still here?
