### ISSUE TITLE
[0.0.4] Move current GUI to component width Projucer gui editor

### ISSUE THREAD

**Issue by ArtemPopof** [abbysoft-team/Soompler#48]
In future releases there would be more components and we need to use Projucer's editor instead of explicitly configuring component position.

**Comment by JorgenPo** [comment]
Hallelujah

**Comment by ArtemPopof** [comment]
Projucer GUI editor is not very usable, lack component rendering and automatic code generation that overrides all changes made by hand drive me insane. I thinks it's better to make some simple editor from scratch, it will be handy if project drop JUCE as framework.
