### ISSUE TITLE
Complainings about "bad" fonts in application

### ISSUE THREAD

**Issue by ArtemPopof** [abbysoft-team/Soompler#6]

**Comment by JorgenPo** [comment]
I think we can use labels instead of keywords in titles (e.g. feature label)

**Comment by JorgenPo** [comment]
Fonts is bad on my opinion

**Comment by ArtemPopof** [comment]
All look-and-feel related issues can wait, just basic gui for now is ok. When all functionality will be ready (few development iterations), any improvements including this one will be reviewed carefully.
