### ISSUE TITLE
[0.0.1] Some JUCE leaks when close app while playing sample

### ISSUE THREAD

**Issue by ArtemPopof** [abbysoft-team/Soompler#9]

**Comment by ArtemPopof** [comment]
FileInputStream and InputStream objects leaked

**Comment by ArtemPopof** [comment]
сannot reproduce

**Comment by ArtemPopof** [comment]
can reproduce again, need to find problematic piece of code

**Comment by JorgenPo** [comment]
Want to fix that, can I reassign it?
